stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .gradle/
    - build/
  key: ${CI_COMMIT_REF_SLUG}

build:
  stage: build
  image: gradle:8.11.1-jdk21-alpine
  script:
    - chmod +x ./gradlew
    - ./gradlew build -x test  # ← Собираем JAR но пропускаем тесты
    - echo "✅ Сборка завершена!"
    - find . -name "*.jar" | head -10  # ← Проверим что собралось
  artifacts:
    paths:
      - build/libs/  # ← Вся папка с артефактами
    expire_in: 1 days
  tags:
    - docker

test:
  stage: test
  image: gradle:8.11.1-jdk21-alpine
  script:
    - chmod +x ./gradlew
    - ./gradlew test
    - echo "✅ Тесты пройдены!"
  tags:
    - docker

deploy:
  stage: deploy
  image: gradle:8.11.1-jdk21-alpine
  script:
    - echo "🚀 Начинаем деплой..."
    - echo "Собранные JAR файлы:"
    - find build/libs/ -name "*.jar" | head -10
    - ls -la build/libs/
    - echo "✅ Деплой завершен!"
  tags:
    - docker
  only:
    - main
    - master
  dependencies:
    - build