stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .gradle/
    - build/

build:
  stage: build
  image: gradle:jdk17-alpine
  script:
    - chmod +x ./gradlew
    - ./gradlew compileJava
    - echo "✅ Сборка завершена!"
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  tags:
    - docker

test:
  stage: test
  image: gradle:jdk17-alpine
  script:
    - chmod +x ./gradlew
    - ./gradlew test
    - echo "✅ Тесты пройдены!"
  tags:
    - docker

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - echo "🚀 Деплой завершен!"
    - echo "Собранные артефакты:"
    - find build/libs/ -name "*.jar" | head -5
  tags:
    - docker
  only:
    - main
    - master