# .gitlab-ci.yml

stages:
  - build
  - test
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  image: maven:3.8-openjdk-17
  script:
    - mvn compile
  tags:
    - docker
  only:
    - main
    - master
    - merge_requests

test:
  stage: test
  image: maven:3.8-openjdk-17
  script:
    - mvn test
  tags:
    - docker
  only:
    - main
    - master
    - merge_requests

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Деплой приложения"
    - echo "Здесь могут быть команды деплоя на сервер"
  tags:
    - docker
  only:
    - main
    - master