stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  paths:
    - .gradle/
    - build/

build:
  stage: build
  image: gradle:jdk17-alpine
  script:
    - gradle compileJava
  tags:
    - docker
  only:
    - main
    - master
    - merge_requests

test:
  stage: test
  image: gradle:jdk17-alpine
  script:
    - gradle test
  tags:
    - docker
  only:
    - main
    - master
    - merge_requests